# -*- coding: utf-8 -*-
"""ChEMBL_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgeqytbRYz1R72HOhpKa-YzFVbxsPRfi
"""

#Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Load and read csv
df = pd.read_csv('Data_9.csv', delimiter=';')
df

act = pd.read_csv('Activity.csv', delimiter=';')
act

#Merge
mydf = pd.merge(df, act, on='ChEMBL ID')
mydf

#Standardise
mydf['Standard'] = np.where(mydf['IC50 unit']=="nm", mydf['IC50 value']*1e-9, mydf['IC50 value']*1e-6)
mydf

#Convert to pIC50
mydf['pIC50'] = -np.log10(mydf['Standard'])
mydf

#Data cleaning
mydf = mydf.dropna(subset = ['Name'])
mydf

"""##My Answer"""

#1. Based on their pIC50 values, what are the names of the least active and most active compounds? Print your output in complete sentences.
mydf.loc[mydf['pIC50'].idxmin(), 'Name']

mydf.loc[mydf['pIC50'].idxmax(), 'Name']

#Print in a full sentence
print(f"The least active compound is {mydf.loc[mydf['pIC50'].idxmin(), 'Name']} and the most active compound is {mydf.loc[mydf['pIC50'].idxmax(), 'Name']}.")

#2. What is the median Polar Surface Area? Print your output in a complete sentence.
np.median(mydf['Polar Surface Area'])
print(f"The median Polar Surface Area is {np.median(mydf['Polar Surface Area'])}.")

#3. The compounds in this dataset belong to different Molecular Species. How many compounds are labelled as 'ACID'? Print your output in a complete sentence.
mydf['Molecular Species'].value_counts()['ACID']
print(f"There are {mydf['Molecular Species'].value_counts()['ACID']} compounds labelled as 'ACID'.")

#4. What is the number of compounds with molecular weights more than 180 and less than 400 g/mol? Print your output in a complete sentence.
mydf[(mydf['Molecular Weight'] > 180) & (mydf['Molecular Weight'] < 400)].shape[0]
print(f"There are {mydf[(mydf['Molecular Weight'] > 180) & (mydf['Molecular Weight'] < 400)].shape[0]} compounds with molecular weights more than 180 and less than 400 g/mol.")

#5. What is the mean and standard deviation of the pIC50 value of the compounds in your dataframe? Print your output in a complete sentence.
mydf['pIC50'].mean()
mydf['pIC50'].std()
print(f"The mean of the pIC50 value is {mydf['pIC50'].mean()} and the standard deviation is {mydf['pIC50'].std()}.")

#6. What are the first, second and third quartiles of the ‘Bioactivities’ values?
mydf['Bioactivities'].quantile([0.25, 0.5, 0.75])

#7. Build one line of code to find the number of compounds for each #RO5 Violations.
mydf['#RO5 Violations'].value_counts()

#8. How many compounds meet the criteria of HBA and HBD less than or equal to 3? Print your answer in a full sentence.
mydf[(mydf['HBA'] <= 3) & (mydf['HBD'] <= 3)].shape[0]
print(f"There are {mydf[(mydf['HBA'] <= 3) & (mydf['HBD'] <= 3)].shape[0]} compounds meet the criteria of HBA and HBD less than or equal to 3.")

#9. What is the statistical summary of the ‘Aromatic Rings’ from the dataset?
mydf['Aromatic Rings'].describe()

#10. Find the minimum and maximum values for both AlogP and CX LogP. Print the output in complete sentences.
mydf[['AlogP', 'CX LogP']].agg(['min', 'max'])

print(f"The minimum value for AlogP and CX LogP are {mydf['AlogP'].min()} and {mydf['CX LogP'].min()}, while the maximum value for AlogP and CX LogP are {mydf['AlogP'].max()} and {mydf['CX LogP'].max()} respectively.")

#11. Filter your dataframe to keep data rows that meet these two requirements: i) Zero rule of 5 Violations (#RO5 Violations), and ii) pIC50 more than 5.0.
filtered = mydf[(mydf['#RO5 Violations'] == 0) & (mydf['pIC50'] > 5.0)]

filtered

#12. Plot a category plot to depict the pIC50 (y-axis) values based on the Molecular species (x-axis). The type of category plot should be boxen. Add a suitable title.
sns.catplot(data = mydf,
            x = 'Molecular Species',
            y = 'pIC50',
            kind = 'boxen')

plt.title('pIC50 values based on the Molecular species')
plt.show()

#13. Plot a set of pair-wise scatter plots to depict the relationship for HBA, HBD, AlogP, Polar Surface Area and Inorganic Flags. The diagonal plot should be in kernel density estimate (kde). The plot’s variable (hue) should be differentiated by the #RO5 Violations. KDE plots should be applied to lower triangle plots. Choose a suitable colour palette.
num_cols = ["HBA", "HBD", "AlogP", "Polar Surface Area", "Inorganic Flag", "#RO5 Violations"]

sns.pairplot(mydf[num_cols],
             vars = ['HBA', 'HBD', 'AlogP', 'Polar Surface Area', 'Inorganic Flag'],
             diag_kind= 'kde',
             hue='#RO5 Violations',
             palette="Set2"
             ).map_lower(sns.kdeplot, cmap="Blues_d")

plt.show()

#14. Create a jointplot to visualise the Molecular weight (y-axis) vs the AlogP (x-axis). The datapoints should be visualised using hexagonal bins. Add the x- and y-axis labels.
sns.jointplot(data = mydf,
              x = 'AlogP',
              y = 'Molecular Weight',
              kind = 'hex')

plt.xlabel('AlogP')
plt.ylabel('Molecular Weight')
plt.show()

#15. Plot a histogram to show the frequency of the pIC50 values. The histogram should have 25 bins. Annotate the histogram with lines to represent the mean, median, minimum and maximum pIC50. Add a suitable title and the legends.
fig, ax = plt.subplots()

plt.hist(mydf['pIC50'],
         bins = 25,
         edgecolor = 'black',
         )

ax.set_xlabel('pIC50')
ax.set_ylabel('Frequency')
ax.set_title('Frequency of the pIC50 values')

mean = np.mean(mydf['pIC50'])
median = np.median(mydf['pIC50'])

ax.axvline (x = mean, color = 'r', label = 'Mean', linestyle = '-', linewidth = 1.5)
ax.axvline (x = median, color = 'r', label = 'Median', linestyle = '--', linewidth = 1.5)

ax.legend()